In [1]:
import pandas as pd

In [2]:
Data = pd.read_csv("C:\\Users\\NISHANT\\3D Objects\\CSV_Files\\IRIS.csv")

In [3]:
pd.options.display.max_rows = 1000

In [4]:
Data

sepal_length  sepal_width  petal_length  petal_width          species
0             5.1          3.5           1.4          0.2      Iris-setosa
1             4.9          3.0           1.4          0.2      Iris-setosa
2             4.7          3.2           1.3          0.2      Iris-setosa
3             4.6          3.1           1.5          0.2      Iris-setosa
4             5.0          3.6           1.4          0.2      Iris-setosa
5             5.4          3.9           1.7          0.4      Iris-setosa
6             4.6          3.4           1.4          0.3      Iris-setosa
7             5.0          3.4           1.5          0.2      Iris-setosa
8             4.4          2.9           1.4          0.2      Iris-setosa
9             4.9          3.1           1.5          0.1      Iris-setosa
10            5.4          3.7           1.5          0.2      Iris-setosa
11            4.8          3.4           1.6          0.2      Iris-setosa
12            4.8          3.0           1.4          0.1      Iris-setosa
13            4.3          3.0           1.1          0.1      Iris-setosa
14            5.8          4.0           1.2          0.2      Iris-setosa
15            5.7          4.4           1.5          0.4      Iris-setosa
16            5.4          3.9           1.3          0.4      Iris-setosa
17            5.1          3.5           1.4          0.3      Iris-setosa
18            5.7          3.8           1.7          0.3      Iris-setosa
19            5.1          3.8           1.5          0.3      Iris-setosa
20            5.4          3.4           1.7          0.2      Iris-setosa
21            5.1          3.7           1.5          0.4      Iris-setosa
22            4.6          3.6           1.0          0.2      Iris-setosa
23            5.1          3.3           1.7          0.5      Iris-setosa
24            4.8          3.4           1.9          0.2      Iris-setosa
25            5.0          3.0           1.6          0.2      Iris-setosa
26            5.0          3.4           1.6          0.4      Iris-setosa
27            5.2          3.5           1.5          0.2      Iris-setosa
28            5.2          3.4           1.4          0.2      Iris-setosa
29            4.7          3.2           1.6          0.2      Iris-setosa
30            4.8          3.1           1.6          0.2      Iris-setosa
31            5.4          3.4           1.5          0.4      Iris-setosa
32            5.2          4.1           1.5          0.1      Iris-setosa
33            5.5          4.2           1.4          0.2      Iris-setosa
34            4.9          3.1           1.5          0.1      Iris-setosa
35            5.0          3.2           1.2          0.2      Iris-setosa
36            5.5          3.5           1.3          0.2      Iris-setosa
37            4.9          3.1           1.5          0.1      Iris-setosa
38            4.4          3.0           1.3          0.2      Iris-setosa
39            5.1          3.4           1.5          0.2      Iris-setosa
40            5.0          3.5           1.3          0.3      Iris-setosa
41            4.5          2.3           1.3          0.3      Iris-setosa
42            4.4          3.2           1.3          0.2      Iris-setosa
43            5.0          3.5           1.6          0.6      Iris-setosa
44            5.1          3.8           1.9          0.4      Iris-setosa
45            4.8          3.0           1.4          0.3      Iris-setosa
46            5.1          3.8           1.6          0.2      Iris-setosa
47            4.6          3.2           1.4          0.2      Iris-setosa
48            5.3          3.7           1.5          0.2      Iris-setosa
49            5.0          3.3           1.4          0.2      Iris-setosa
50            7.0          3.2           4.7          1.4  Iris-versicolor
51            6.4          3.2           4.5          1.5  Iris-versicolor
52            6.9          3.1

In [5]:
X = Data.iloc[:,[0,1,2,3]].values

In [6]:
Y = Data.iloc[:,4].values

In [11]:
from sklearn.model_selection import RepeatedKFold
import numpy as np

In [14]:
kf = RepeatedKFold(n_splits = 5,n_repeats = 10, random_state = None)

In [18]:
for train_index , test_index in kf.split(X):
    print("Train:",train_index,"Validation:",test_index)
    x_train,x_test = X[train_index],X[test_index]
    y_train,y_test = Y[train_index],Y[test_index]
    print("\ntraining set:", x_train, y_train)
    print("\nvalidation set :", x_test, y_test)

Train: [  0   2   4   5   6   7   8   9  10  11  12  13  14  15  16  18  19  21
  22  23  24  25  26  27  28  29  33  34  35  36  37  38  39  40  41  42
  43  44  45  48  50  51  52  53  54  55  56  57  59  61  62  63  64  67
  68  70  71  73  74  75  76  78  79  80  81  83  85  86  87  88  89  90
  91  93  96  97  99 100 101 102 103 104 105 106 107 108 109 110 112 113
 114 115 116 117 118 119 120 121 123 124 125 128 129 130 131 132 133 134
 135 136 137 139 140 141 142 143 146 147 148 149] Validation: [  1   3  17  20  30  31  32  46  47  49  58  60  65  66  69  72  77  82
  84  92  94  95  98 111 122 126 127 138 144 145]

training set: [[5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1. 